name: rc2_snakemake
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - blast
  - diamond
  - mafft
  - fasttree
  - ncbi-genome-download
  - toolz
  - biopython=1.77
  - pandas
  - numpy
  - networkx
  - snakemake