cleannames: ./data/cleannames.txt
download_genbank:
  options: 'no'
genus: data/genus.txt
outdir: test-output
previous_files: concatenated_ribos.fasta
protein_dna:
  options: protein
report: report.html
ribo_name_field:
  options: 0
ribosomefile: ./data/atccs.txt
threads: 4
tree_type:
  options: iqtree
workflow_dir: ./workflow
