threads: 4
download_genbank:
      options: "no"
tree_type:
      options: "fasttree"
protein_dna:
      options: "protein"
ribosomefile: "data/atccs.txt"
genus: "data/genus.txt"
cleannames:
      "data/cleannames.txt"
ribo_name_field:
      options: 0
report: "report.html"
previous_files: False
outdir: False
converted_nuc: False
workflow_dir: False
